channels:
- conda-forge
- defaults
- s3://a8c-conda/data-science/
dependencies:
- Flask=1.1
- gensim=3.8
- hypothesis=5.9
- ipython=6
- mock=4.0
- numexpr=2.6
- pip=19
- py=1.5
- pycodestyle=2.5
- pydocstyle=5.0
- pylint=2.3
- pytest=4.3
- pytest-mock=1.10
- python=3.7
- slacker=0.14
- spacy=2.0
- scikit-learn=0.21.2
- scipy=1.2
- pip:
  - aspy.yaml==1.0.0
  - cached-property==1.3.1
  - defopt==3.2.0
  - nodeenv==1.2.0
  - pockets==0.5.1
  - pre-commit==0.14.2
  - prompt-toolkit==1.0.15
  - pylint-quotes==0.1.7
  - sphinxcontrib-napoleon==0.6.1
  - webtest==2.0.28
